import cv2
face_cascade = cv2.CascadeClassifier(‘haarcascade_frontalface_default.xml’)
cap = cv2.VideoCapture(“elon.jpg”)
ret, img = cap.read()
gray = cv2.cvtColor(img, cv2.COLOR_BR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
cv2.imshow(‘img’, img)
cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()